function valid = condition_check(y0, y1, y2)
% Sprawdza, czy wartości y0, y1, y2 spełniają wymagane warunki (są 
% rzeczywiste, skończone i różne od siebie)
% Autor: Andrii Voznesenskyi

    valid = (isreal(y0) && isreal(y1) && isreal(y2) && ...
            isfinite(y0) && isfinite(y1) && isfinite(y2) && ...
            y0 ~= y1 && y1 ~= y2 && y0 ~= y2) || ...
            (isreal(y0) && isreal(y1) && isreal(y2) && ...
            isfinite(y0) && isfinite(y1) && isfinite(y2));
end